version: '3.3'

services: 
  container-node:
    build:
      context: ./
      dockerfile: ./node/Dockerfile
    image: container-node
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app